export const MAP_PROPS_TO_ICON = {
  cart: './cart.svg',
  eye: './eye.svg',
  cardTrash: './card-trash',
  favorites: './favorites',
  appleLogo: './apple-logo',
  categoryCamera: './cateogry-camera',
  categoryCellPhone: './category-cell-phone',
  categoryComputer: './category-computer',
  categoryGamepad: './category-gamepad',
  categoryHeadphone: './category-headphone',
  categorySmartWatch: './category-smartwatch',
  categoryCancellations: './category-cancellations',
  dropdownLogout: './dropdown-logout',
  dropdownOrder: './dropdown-order',
  dropdownReviews: './dropdown-rewiews',
  dropdownUser: './dropdown-user',
  facebook: './facebook',
  twitter: './twitter',
  instagram: './instagram',
  menuArrow: './menu-arraow',
  propmoArrowWhite: './promo-arrow-white',
  sectionArrowLeft: './section-arrow-left',
  sectionArrowRight: './section-arrow-right',
  serviceFast: './service-fast',
  serviceMoney: './service-money',
  serviceCustomer: './service-customer',
};
